const employees = [
  {
    id: 1,
    name: "Sabrina",
    surname: "Briza",
    photo: "https://randomuser.me/api/portraits/women/1.jpg",
    role: "CEO",
    team: "Marketing",
    managerId: null,
    description: "CEO do Projeto Reviva em conjunto com Bruna Souza",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 2,
    name: "Bruna",
    surname: "Souza",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    role: "CEO",
    team: "Marketing",
    // managerId: null,
    description: "CEO do Projeto Reviva em conjunto com Bruna Souza",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 3,
    name: "Ana",
    surname: "Micheloni",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    role: "Gestora",
    team: "Administração",
    managerId: 1,
    description: "Gestora do Projeto de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 4,
    name: "Mariana",
    surname: "Dantas",
    photo: "https://randomuser.me/api/portraits/women/5.jpg",
    role: "Gestora",
    team: "Marketing",
    managerId: 1,
    description: "Gestora do Projeto de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 5,
    name: "Marcelo",
    surname: "Izidoro",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    role: "Gestor",
    team: "Pesquisa",
    managerId: 1,
    description: "Gestor do Projeto de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 6,
    name: "Larissa",
    surname: "Mendes",
    photo: "https://randomuser.me/api/portraits/women/3.jpg",
    role: "Gestora",
    team: "Recursos Humanos",
    managerId: 1,
    description: "Gestora do Projeto de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 7,
    name: "Paulo",
    surname: "Alvares",
    photo: "./assets/eu.jpg",
    role: "Gestor",
    team: "Tecnologia",
    managerId: 1,
    description: "Gestor do Projeto de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 8,
    name: "Caetano",
    surname: "de Paula",
    photo: "https://randomuser.me/api/portraits/men/2.jpg",
    role: "Analista",
    team: "Tecnologia",
    managerId: 7,
    description: "Analista do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 9,
    name: "Cauê",
    surname: "Costa",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    role: "Documentador",
    team: "Tecnologia",
    managerId: 7,
    description: "Documentador do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 10,
    name: "César",
    surname: "Augusto",
    photo: "https://randomuser.me/api/portraits/men/4.jpg",
    role: "Especialista",
    team: "Tecnologia",
    managerId: 7,
    description: "Especialista do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 11,
    name: "Erick",
    surname: "Augusto",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 7,
    description: "Desenvolvedor do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 12,
    name: "Gustavo",
    surname: "Saraiva",
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 7,
    description: "Desenvolvedor do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 13,
    name: "Isabela",
    surname: "Dias",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    role: "Designer UX",
    team: "Tecnologia",
    managerId: 7,
    description: "Designer do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 14,
    name: "João",
    surname: "Ferreira",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 7,
    description: "Desenvolvedor do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];
