const employees = [
  {
    id: 1,
    name: "Sabrina",
    surname: "Briza",
    photo: "https://randomuser.me/api/portraits/women/1.jpg",
    role: "CEO",
    team: "Marketing",
    managerId: null,
    description: "CEO do Projeto Reviva em conjunto com Bruna Souza",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 2,
    name: "Bruna",
    surname: "Souza",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    role: "CEO",
    team: "Marketing",
    managerId: 4,
    description: "CEO do Projeto Reviva em conjunto com Bruna Souza",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 3,
    name: "Ana",
    surname: "Micheloni",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    role: "Gestora",
    team: "Administração",
    managerId: 1,
    description: "Gestora do Projeto de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 4,
    name: "Mariana",
    surname: "Dantas",
    photo: "https://randomuser.me/api/portraits/women/5.jpg",
    role: "Gestora",
    team: "Marketing",
    managerId: 1,
    description: "Gestora do Projeto de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 5,
    name: "Marcelo",
    surname: "Izidoro",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    role: "Gestor",
    team: "Pesquisa",
    managerId: 1,
    description: "Gestor do Projeto de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 6,
    name: "Larissa",
    surname: "Mendes",
    photo: "https://randomuser.me/api/portraits/women/3.jpg",
    role: "Gestora",
    team: "Recursos Humanos",
    managerId: 1,
    description: "Gestora do Projeto de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 7,
    name: "Paulo",
    surname: "Alvares",
    photo: "./assets/eu.jpg",
    role: "Gestor",
    team: "Tecnologia",
    managerId: 1,
    description: "Gestor do Projeto de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 8,
    name: "Caetano",
    surname: "de Paula",
    photo: "https://randomuser.me/api/portraits/men/2.jpg",
    role: "Analista",
    team: "Tecnologia",
    managerId: 7,
    description: "Analista do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 9,
    name: "Cauê",
    surname: "Costa",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    role: "Documentador",
    team: "Tecnologia",
    managerId: 7,
    description: "Documentador do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 10,
    name: "César",
    surname: "Augusto",
    photo: "https://randomuser.me/api/portraits/men/4.jpg",
    role: "Especialista",
    team: "Tecnologia",
    managerId: 7,
    description: "Especialista do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 11,
    name: "Erick",
    surname: "Augusto",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 7,
    description: "Desenvolvedor do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 12,
    name: "Gustavo",
    surname: "Saraiva",
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 7,
    description: "Desenvolvedor do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 13,
    name: "Isabela",
    surname: "Dias",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    role: "Designer UX",
    team: "Tecnologia",
    managerId: 7,
    description: "Designer do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 14,
    name: "João",
    surname: "Ferreira",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 7,
    description: "Desenvolvedor do Projetos de Tecnologia",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 15,
    name: "Bianca",
    surname: "de Souza",
    photo: "https://randomuser.me/api/portraits/women/7.jpg",
    role: "Analista",
    team: "Administração",
    managerId: 3,
    description: "Analista do Projetos de Administração",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 16,
    name: "Gustavo",
    surname: "Formigoni",
    photo: "https://randomuser.me/api/portraits/men/8.jpg",
    role: "Analista",
    team: "Administração",
    managerId: 3,
    description: "Analista do Projetos de Administração",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 17,
    name: "Isabella",
    surname: "Fernandes",
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
    role: "Analista",
    team: "Administração",
    managerId: 3,
    description: "Analista do Projetos de Administração",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 18,
    name: "Mariana",
    surname: "Mello",
    photo: "https://randomuser.me/api/portraits/women/9.jpg",
    role: "Especialista",
    team: "Administração",
    managerId: 3,
    description: "Especialista do Projetos de Administração",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 19,
    name: "Vitória",
    surname: "Juviniano",
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    role: "Especialista",
    team: "Administração",
    managerId: 3,
    description: "Especialista do Projetos de Administração",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 19,
    name: "Ana",
    surname: "Alice",
    photo: "https://randomuser.me/api/portraits/women/11.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 4,
    description: "Analista do Projetos de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 20,
    name: "Gabriella",
    surname: "Fernandes",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 4,
    description: "Analista do Projetos de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 21,
    name: "João",
    surname: "Pedro",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    role: "Especialista",
    team: "Marketing",
    managerId: 4,
    description: "Especialista do Projetos de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 22,
    name: "Maria",
    surname: "Luiza",
    photo: "https://randomuser.me/api/portraits/women/13.jpg",
    role: "Especialista",
    team: "Marketing",
    managerId: 4,
    description: "Especialista do Projetos de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 23,
    name: "Murilo",
    surname: "Villalba",
    photo: "https://randomuser.me/api/portraits/men/10.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 4,
    description: "Analista do Projetos de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 24,
    name: "Rebeca",
    surname: "Martins",
    photo: "https://randomuser.me/api/portraits/women/14.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 4,
    description: "Analista do Projetos de Marketing",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 25,
    name: "Augusto",
    surname: "Melo",
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
    role: "Coordenador",
    team: "Pesquisa",
    managerId: 5,
    description: "Coordenador do Projetos de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 26,
    name: "Felipe",
    surname: "Garcia",
    photo: "https://randomuser.me/api/portraits/men/12.jpg",
    role: "Coordenador",
    team: "Pesquisa",
    managerId: 5,
    description: "Coordenador do Projetos de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 27,
    name: "Gabriel",
    surname: "Abat",
    photo: "https://randomuser.me/api/portraits/men/13.jpg",
    role: "Analista",
    team: "Pesquisa",
    managerId: 5,
    description: "Analista do Projetos de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 28,
    name: "Gustavo",
    surname: "de Sales",
    photo: "https://randomuser.me/api/portraits/men/14.jpg",
    role: "Pesquisador",
    team: "Pesquisa",
    managerId: 5,
    description: "Pesquisador do Projetos de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 29,
    name: "Isabelly",
    surname: "Magalhães",
    photo: "https://randomuser.me/api/portraits/women/15.jpg",
    role: "Pesquisadora",
    team: "Pesquisa",
    managerId: 5,
    description: "Pesquisadora do Projetos de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 30,
    name: "Marina",
    surname: "Lima",
    photo: "https://randomuser.me/api/portraits/women/16.jpg",
    role: "Pesquisadora",
    team: "Pesquisa",
    managerId: 5,
    description: "Pesquisadora do Projetos de Pesquisa",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 30,
    name: "Amanda",
    surname: "Marques",
    photo: "https://randomuser.me/api/portraits/women/17.jpg",
    role: "Analista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Analista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 31,
    name: "Camila",
    surname: "Lima",
    photo: "https://randomuser.me/api/portraits/women/18.jpg",
    role: "Analista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Analista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 32,
    name: "Julia",
    surname: "Santos",
    photo: "https://randomuser.me/api/portraits/women/22.jpg",
    role: "Especialista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Especialista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 33,
    name: "Maria Eduarda",
    surname: "Benício",
    photo: "https://randomuser.me/api/portraits/women/19.jpg",
    role: "Especialista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Especialista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 34,
    name: "Maria Eduarda",
    surname: "Camargo",
    photo: "https://randomuser.me/api/portraits/women/20.jpg",
    role: "Analista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Analista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 35,
    name: "Nathalia",
    surname: "Barrochello",
    photo: "https://randomuser.me/api/portraits/women/21.jpg",
    role: "Analista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Analista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 36,
    name: "Samuel",
    surname: "Lopes",
    photo: "https://randomuser.me/api/portraits/men/14.jpg",
    role: "Analista",
    team: "Recursos Humanos",
    managerId: 6,
    description: "Analista do Projetos de Recursos Humanos",
    responsibilities:
      "lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];
