const employees = [
  {
    id: 1,
    name: "Sabrina",
    surname: "Agata",
    photo: "../assets/team/sabrina.jpg",
    role: "Diretora",
    team: "Marketing",
    managerId: null,
    description: "Diretora da ReViva",
    responsibilities: "Administrar o Projeto Reviva e os seus colaboradores",
  },
  {
    id: 2,
    name: "Ana",
    surname: "Julia",
    photo: "../assets/team/administracao/ana.jpg",
    role: "Gestora - ADM",
    team: "Administração",
    managerId: 1,
    description: "Gestora do grupo de administração do Projeto Reviva",
    responsibilities:
      "Gerenciar o time de administração, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros gestores.",
  },
  {
    id: 3,
    name: "Mariana",
    surname: "Dantas",
    photo: "../assets/team/marketing/mariana.jpg",
    role: "Gestora - Marketing",
    team: "Marketing",
    managerId: 1,
    description: "Gestora do grupo de marketing do Projeto Reviva",
    responsibilities:
      "Gerenciar o time de marketing, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros gestores.",
  },
  {
    id: 4,
    name: "Marcelo",
    surname: "Izidoro",
    photo: "../assets/team/pesquisa/marcelo.jpg",
    role: "Gestor - Pesquisa",
    team: "Pesquisa",
    managerId: 1,
    description: "Gestor do grupo de pesquisa do Projeto Reviva",
    responsibilities:
      "Gerenciar o time de pesquisa, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros gestores.",
  },
  {
    id: 5,
    name: "Samuel",
    surname: "Lopes",
    photo: "../assets/team/rh/samuel.jpg",
    role: "Gestor - RH",
    team: "Recursos Humanos",
    managerId: 1,
    description: "Gestor do grupo de recursos humanos do Projeto Reviva",
    responsibilities:
      "Gerenciar o time de recursos humanos, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros gestores.",
  },
  {
    id: 6,
    name: "Paulo",
    surname: "Alvares",
    photo: "../assets/team/ti/paulo.jpg",
    role: "Gestor - TI",
    team: "Tecnologia",
    managerId: 1,
    description: "Gestor do grupo de tecnologia do Projeto Reviva",
    responsibilities:
      "Gerenciar o time de tecnologia, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros gestores.",
  },
  {
    id: 7,
    name: "Caetano",
    surname: "de Paula",
    photo: "./assets/team/ti/caetano.jpg",
    role: "Especialista",
    team: "Tecnologia",
    managerId: 6,
    description: "Consultor técnico dos projetos de tecnologia",
    responsibilities:
      "Responsável por ensinar tecnologias diversas aos colaboradores.",
  },
  {
    id: 8,
    name: "Cauê",
    surname: "Costa",
    photo: "./assets/team/ti/caue.jpg",
    role: "Documentador",
    team: "Tecnologia",
    managerId: 6,
    description: "Documentador dos projetos de tecnologia",
    responsibilities:
      "Responsável diretamente pela documentação dos projetos de tecnologia. Desde o projeto inicial, passando pela fase de desenvolvimento, testes e entrega.",
  },
  {
    id: 9,
    name: "César",
    surname: "Augusto",
    photo: "./assets/team/ti/cesar.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 6,
    description: "Desenvolvedor dos projetos de tecnologia",
    responsibilities:
      "Gerenciador de banco de dados da equipe, comportando os materiais de desenvolvimento a serem consumidos no site, como imagens, textos, etc.",
  },
  {
    id: 10,
    name: "Erick",
    surname: "Augusto",
    photo: "./assets/team/ti/erick.jpg",
    role: "Analista",
    team: "Tecnologia",
    managerId: 6,
    description: "Analista dos projetos de tecnologia",
    responsibilities:
      "Responsável por testes e camadas de qualidade dos projetos desenvolvidos pelo time.",
  },
  {
    id: 11,
    name: "Gabriel",
    surname: "Camargo",
    photo: "./assets/team/ti/camargo.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 6,
    description: "Desenvolvedor dos projetos de Tecnologia",
    responsibilities:
      "Responsável por desenvolvimento dos projetos de tecnologia para o site.",
  },
  {
    id: 12,
    name: "Isabela",
    surname: "Dias",
    photo: "./assets/team/ti/isa.jpg",
    role: "Designer UX",
    team: "Tecnologia",
    managerId: 6,
    description: "Designer dos projetos de tecnologia",
    responsibilities:
      "Responsável pelo design dos projetos, integração com o time de marketing para montagem de planos, mudanças e decisões criativas.",
  },
  {
    id: 13,
    name: "Lucas",
    surname: "Alison",
    photo: "./assets/team/ti/lucas.jpg",
    role: "Desenvolvedor",
    team: "Tecnologia",
    managerId: 6,
    description: "Desenvolvedor dos projetos de tecnologia",
    responsibilities:
      "Responsável por desenvolvimento dos projetos de tecnologia para o site.",
  },
  {
    id: 14,
    name: "Gustavo",
    surname: "Formigoni",
    photo: "./assets/team/administracao/gustavo.jpg",
    role: "Sup. de Comunicação",
    team: "Administração",
    managerId: 2,
    description:
      "Supervisor do time de administração da ReViva e pilar para o projeto de comunicação interna",
    responsibilities:
      "Liderar o time de administração para tarefas de comunicação interna, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros supervisores.",
  },
  {
    id: 15,
    name: "Mariana",
    surname: "Mello",
    photo: "./assets/team/administracao/mariana-mello.jpg",
    role: "Sup. de Auditoria",
    team: "Administração",
    managerId: 2,
    description:
      "Supervisora do time de administração da ReViva e pilar para o projeto de auditoria",
    responsibilities:
      "Liderar o time de administração para tarefas de auditoria, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros supervisores.",
  },
  {
    id: 16,
    name: "Vitória",
    surname: "Juviniano",
    photo: "./assets/team/administracao/vitoria.jpg",
    role: "Sup. de Planejamento",
    team: "Administração",
    managerId: 2,
    description:
      "Supervisor do time de administração da ReViva e pilar para o projeto de planejamento",
    responsibilities:
      "Liderar o time de administração para tarefas de planejamento, coordenando o trabalho dos seus colaboradores. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros supervisores.",
  },
  {
    id: 17,
    name: "Maria",
    surname: "Eduarda",
    photo: "./assets/team/administracao/maria-eduarda.jpg",
    role: "Ass. de Comunicação",
    team: "Administração",
    managerId: 14,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de comunicação e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 18,
    name: "Mariana",
    surname: "Bressani",
    photo: "./assets/team/administracao/mariana-bressani.jpg",
    role: "Ass. de Comunicação",
    team: "Administração",
    managerId: 14,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de comunicação e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 19,
    name: "Matheus",
    surname: "",
    photo: "./assets/team/administracao/matheus.jpg",
    role: "Ass. de Comunicação",
    team: "Administração",
    managerId: 14,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de comunicação e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 20,
    name: "Maria",
    surname: "Beatriz",
    photo: "./assets/team/administracao/maria-beatriz.jpg",
    role: "Ass. de Auditoria",
    team: "Administração",
    managerId: 15,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de auditoria e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 21,
    name: "Isabella",
    surname: "Vitória",
    photo: "./assets/team/administracao/isabella.jpg",
    role: "Ass. de Auditoria",
    team: "Administração",
    managerId: 15,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de auditoria e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 22,
    name: "Bianca",
    surname: "de Souza",
    photo: "./assets/team/administracao/bianca.jpg",
    role: "Ass. de Planejamento",
    team: "Administração",
    managerId: 16,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de planejamento e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 23,
    name: "Guilherme",
    surname: "Ramos",
    photo: "./assets/team/administracao/guilherme.jpg",
    role: "Ass. de Planejamento",
    team: "Administração",
    managerId: 16,
    description: "Assistente do time de administração da ReViva",
    responsibilities:
      "Fiscalizar os processos de planejamento e garantir que eles sejam eficientes e eficazes. Ser pilar da equipe e garantir que os processos sejam eficientes e eficazes em conjunto com outros assistentes.",
  },
  {
    id: 24,
    name: "Ana",
    surname: "Alice",
    photo: "./assets/team/marketing/ana-alice.jpg",
    role: "Assistente",
    team: "Marketing",
    managerId: 3,
    description: "Assistente do time de marketing da ReViva",
    responsibilities:
      "Ajudar a equipe a alcancar seus objetivos com montagem de planos de marketing.",
  },
  {
    id: 25,
    name: "Bruna",
    surname: "Souza",
    photo: "../assets/team/marketing/bruna.jpg",
    role: "Assistente",
    team: "Marketing",
    managerId: 3,
    description: "Assistente do time de marketing da ReViva",
    responsibilities:
      "Ajudar a equipe a alcancar seus objetivos com montagem de planos de marketing.",
  },
  {
    id: 26,
    name: "Gabriella",
    surname: "Fernandes",
    photo: "./assets/team/marketing/gabi.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 3,
    description: "Analista dos projetos de Marketing da ReViva",
    responsibilities:
      "Revisão de conteúdo e atribuição dos mesmos aos colaboradores.",
  },
  {
    id: 27,
    name: "João",
    surname: "Pedro",
    photo: "./assets/team/marketing/joao.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 3,
    description: "Analista de projetos de Marketing da ReViva",
    responsibilities:
      "Revisão de conteúdo e atribuição dos mesmos aos colaboradores.",
  },
  {
    id: 28,
    name: "Kemilly",
    surname: "Silva",
    photo: "./assets/team/marketing/kemilly.jpg",
    role: "Editora de Vídeos",
    team: "Marketing",
    managerId: 3,
    description: "Editora de Vídeos dos projetos de Marketing",
    responsibilities:
      "Responsável por montagem e publicação dos vídeos da equipe.",
  },
  {
    id: 29,
    name: "Maria",
    surname: "Luiza",
    photo: "./assets/team/marketing/maria-luiza.jpg",
    role: "Analista",
    team: "Marketing",
    managerId: 3,
    description: "Analista de projetos de Marketing",
    responsibilities:
      "Revisão de conteúdo e atribuição dos mesmos aos colaboradores.",
  },
  {
    id: 30,
    name: "Michael",
    surname: "Ferreira",
    photo: "./assets/team/marketing/michael.jpg",
    role: "Designer",
    team: "Marketing",
    managerId: 3,
    description: "Designer dos projetos de Marketing",
    responsibilities:
      "Criação de layouts e protótipos para os projetos de marketing.",
  },
  {
    id: 31,
    name: "Murilo",
    surname: "Bernardo",
    photo: "./assets/team/marketing/murilo.jpg",
    role: "Social Media",
    team: "Marketing",
    managerId: 3,
    description: "Social Media dos projetos de Marketing",
    responsibilities:
      "Responsável por montagem e publicação de postagens nas redes sociais.",
  },
  {
    id: 32,
    name: "Rebeca",
    surname: "Martins",
    photo: "./assets/team/marketing/rebeca.jpg",
    role: "Social Media",
    team: "Marketing",
    managerId: 3,
    description: "Social Media dos projetos de Marketing",
    responsibilities:
      "Responsável por montagem e publicação de postagens nas redes sociais.",
  },
  {
    id: 33,
    name: "Ana",
    surname: "Beatriz",
    photo: "./assets/team/pesquisa/ana-beatriz.jpg",
    role: "Relatora Técnica",
    team: "Pesquisa",
    managerId: 4,
    description: "Relatora Técnica dos projetos de Pesquisa",
    responsibilities:
      "Responsável por montagem dos relatórios dos projetos de pesquisa.",
  },
  {
    id: 34,
    name: "Augusto",
    surname: "Melo",
    photo: "./assets/team/pesquisa/augusto.jpg",
    role: "Relator Técnico",
    team: "Pesquisa",
    managerId: 4,
    description: "Relator Técnico dos projetos de Pesquisa",
    responsibilities:
      "Responsável por montagem dos relatórios dos projetos de pesquisa.",
  },
  {
    id: 35,
    name: "Felipe",
    surname: "Garcia",
    photo: "./assets/team/pesquisa/felipe.jpg",
    role: "Analista de Conteúdo",
    team: "Pesquisa",
    managerId: 4,
    description: "Analista de conteúdo dos projetos de Pesquisa",
    responsibilities:
      "Responsável por montagem das análises dos projetos de pesquisa.",
  },
  {
    id: 36,
    name: "Gabriel",
    surname: "Abat",
    photo: "./assets/team/pesquisa/gabriel.jpg",
    role: "Seletor de Fontes",
    team: "Pesquisa",
    managerId: 4,
    description: "Seletor de fontes dos projetos de Pesquisa",
    responsibilities:
      "Responsável por busca de fontes de pesquisa dos projetos de pesquisa.",
  },
  {
    id: 37,
    name: "Gustavo",
    surname: "Lima",
    photo: "./assets/team/pesquisa/sales.jpg",
    role: "Planejador Estratégico",
    team: "Pesquisa",
    managerId: 4,
    description: "Planejador estratégico dos projetos de Pesquisa e oficinas",
    responsibilities:
      "Responsável por elaborar estratégias de pesquisa e oficinas.",
  },
  {
    id: 38,
    name: "Lucas",
    surname: "Henrique",
    photo: "./assets/team/pesquisa/lucas.jpg",
    role: "Seletor de Fontes",
    team: "Pesquisa",
    managerId: 4,
    description: "Seletor de fontes dos projetos de Pesquisa",
    responsibilities:
      "Responsável por busca de fontes de pesquisa dos projetos de pesquisa.",
  },
  {
    id: 39,
    name: "Marina",
    surname: "Lima",
    photo: "./assets/team/pesquisa/marina.jpg",
    role: "Analista de Conteúdo",
    team: "Pesquisa",
    managerId: 4,
    description: "Analista de conteúdo dos projetos de Pesquisa",
    responsibilities:
      "Responsável por montagem das análises dos projetos de pesquisa.",
  },
  {
    id: 40,
    name: "Amanda",
    surname: "Marques",
    photo: "./assets/team/rh/amanda.jpg",
    role: "Atração e Seleção",
    team: "Recursos Humanos",
    managerId: 5,
    description: "Atração e Seleção de pessoas para ReViva",
    responsibilities: "Responsável por administrar as pessoas dos times.",
  },
  {
    id: 41,
    name: "Eliseu",
    surname: "",
    photo: "./assets/team/rh/eliseu.jpg",
    role: "DHO",
    team: "Recursos Humanos",
    managerId: 5,
    description: "DHO do Recursos Humanos",
    responsibilities: "Responsável por administrar as pessoas dos times.",
  },
  {
    id: 42,
    name: "Maria",
    surname: "Eduarda",
    photo: "./assets/team/rh/maria-eduarda.jpg",
    role: "DHO",
    team: "Recursos Humanos",
    managerId: 5,
    description: "DHO do Recursos Humanos",
    responsibilities: "Responsável por administrar as pessoas dos times.",
  },
  {
    id: 43,
    name: "Nathalia",
    surname: "Barrochello",
    photo: "./assets/team/rh/nathalia.jpg",
    role: "Atração e Seleção",
    team: "Recursos Humanos",
    managerId: 5,
    description: "Atração e Seleção de pessoas para ReViva",
    responsibilities: "Responsável por administrar as pessoas dos times.",
  },
];
